# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_auto_pc_0/custom_mem_auto_pc_0.xci
# IP: The module: 'custom_mem_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_auto_pc_0/custom_mem_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'custom_mem_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_auto_pc_0/custom_mem_auto_pc_0.xci
# IP: The module: 'custom_mem_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_auto_pc_0/custom_mem_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'custom_mem_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
