# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/jay/Kanish/custom_memory/custom_memory.cache/wt [current_project]
set_property parent.project_path /home/jay/Kanish/custom_memory/custom_memory.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths /home/jay/Kanish/ip_repo/myip_custom_mem_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo /home/jay/Kanish/custom_memory/custom_memory.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/hdl/custom_mem_wrapper.v
add_files /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/custom_mem.bd
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_processing_system7_0_0/custom_mem_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_auto_pc_0/custom_mem_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_rst_ps7_0_100M_0/custom_mem_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_rst_ps7_0_100M_0/custom_mem_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_rst_ps7_0_100M_0/custom_mem_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_system_ila_0_0/bd_0/ip/ip_0/bd_dc54_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_system_ila_0_0/bd_0/bd_dc54_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/ip/custom_mem_system_ila_0_0/custom_mem_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jay/Kanish/custom_memory/custom_memory.srcs/sources_1/bd/custom_mem/custom_mem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top custom_mem_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef custom_mem_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file custom_mem_wrapper_utilization_synth.rpt -pb custom_mem_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
