# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/custom_mem/custom_mem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_mem || ORIG_REF_NAME==custom_mem} -quiet] -quiet

# IP: bd/custom_mem/ip/custom_mem_processing_system7_0_0/custom_mem_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_mem_processing_system7_0_0 || ORIG_REF_NAME==custom_mem_processing_system7_0_0} -quiet] -quiet

# IP: bd/custom_mem/ip/custom_mem_myip_custom_mem_0_1/custom_mem_myip_custom_mem_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_mem_myip_custom_mem_0_1 || ORIG_REF_NAME==custom_mem_myip_custom_mem_0_1} -quiet] -quiet

# IP: bd/custom_mem/ip/custom_mem_auto_pc_0/custom_mem_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_mem_auto_pc_0 || ORIG_REF_NAME==custom_mem_auto_pc_0} -quiet] -quiet

# IP: bd/custom_mem/ip/custom_mem_ps7_0_axi_periph_0/custom_mem_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_mem_ps7_0_axi_periph_0 || ORIG_REF_NAME==custom_mem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/custom_mem/ip/custom_mem_rst_ps7_0_100M_0/custom_mem_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_mem_rst_ps7_0_100M_0 || ORIG_REF_NAME==custom_mem_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/custom_mem/ip/custom_mem_address_logic_0_0/custom_mem_address_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_mem_address_logic_0_0 || ORIG_REF_NAME==custom_mem_address_logic_0_0} -quiet] -quiet

# IP: bd/custom_mem/ip/custom_mem_system_ila_0_0/custom_mem_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_mem_system_ila_0_0 || ORIG_REF_NAME==custom_mem_system_ila_0_0} -quiet] -quiet

# XDC: bd/custom_mem/custom_mem_ooc.xdc
